
tame.catchExceptions ();

function foo (cb) {

    await setTimeout (defer (), 10);
    throw new Error ("shit!")
    cb(10);
}

function bar (cb) {
    var d = {};
    await foo (defer (d.x));
    cb();
}

function baz () {
   await setTimeout (defer (), 10);
   await bar (defer ());
};

baz ();
